"""Verify the frozen Phase 13 benchmark and emit a machine acceptance record."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from crossmarket_agentgym.benchmarking.core import verify_benchmark


def _count(root: Path, pattern: str) -> int:
    return sum(1 for path in root.glob(pattern) if path.is_file())


def build_acceptance(
    benchmark: Path,
    *,
    review_approved: bool = False,
    p0_count: int | None = None,
    p1_count: int | None = None,
) -> dict[str, Any]:
    """Return the non-review Phase 13 acceptance state."""
    result = verify_benchmark(benchmark)
    table_counts = {
        suffix: _count(benchmark / "tables", f"*.{suffix}")
        for suffix in ("csv", "tex", "md", "html")
    }
    writable_files = [
        path.relative_to(benchmark).as_posix()
        for path in benchmark.rglob("*")
        if path.is_file() and path.stat().st_mode & 0o200
    ]
    machine_ready = (
        result.is_valid
        and result.run_count == 215
        and table_counts == {"csv": 9, "tex": 9, "md": 9, "html": 9}
        and _count(benchmark / "figures", "*.svg") == 10
        and not writable_files
    )
    review_ready = (
        review_approved and p0_count == 0 and p1_count == 0
    )
    phase_complete = machine_ready and review_ready
    return {
        "schema_version": "1.0",
        "phase": 13,
        "benchmark_id": result.benchmark_id,
        "benchmark_path": benchmark.as_posix(),
        "machine_acceptance_passed": machine_ready,
        "phase13_complete": phase_complete,
        "phase14_ready": phase_complete,
        "sole_blocker": (
            None
            if phase_complete
            else "NON_AUTHOR_BENCHMARK_REVIEW_MISSING"
            if machine_ready
            else "MACHINE_GATE_FAILED"
        ),
        "run_count": result.run_count,
        "checksummed_file_count": result.file_count,
        "table_counts": table_counts,
        "figure_svg_count": _count(benchmark / "figures", "*.svg"),
        "agent_log_file_count": _count(benchmark / "agent_logs", "**/*"),
        "hpo_report_count": _count(
            benchmark / "tuning_logs", "*/study_report.json"
        ),
        "writable_files": writable_files,
        "checks": [
            check.model_dump(mode="json") for check in result.checks
        ],
        "review_note": (
            "No review identity or approval is generated by this script. "
            "The review flags record an externally supplied disposition."
        ),
        "review_disposition": {
            "confirmation_source": "project_owner" if review_ready else None,
            "benchmark_approved": review_approved,
            "p0_count": p0_count,
            "p1_count": p1_count,
            "review_artifact_persisted": False,
        },
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--benchmark",
        type=Path,
        default=Path("benchmarks/v1"),
    )
    parser.add_argument("--output", type=Path)
    parser.add_argument("--review-approved", action="store_true")
    parser.add_argument("--p0-count", type=int)
    parser.add_argument("--p1-count", type=int)
    arguments = parser.parse_args()
    payload = build_acceptance(
        arguments.benchmark,
        review_approved=arguments.review_approved,
        p0_count=arguments.p0_count,
        p1_count=arguments.p1_count,
    )
    text = json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    if arguments.output is not None:
        arguments.output.parent.mkdir(parents=True, exist_ok=True)
        arguments.output.write_text(text, encoding="utf-8", newline="\n")
    print(text, end="")
    return 0 if payload["machine_acceptance_passed"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
